application: think-app 
version: 12
runtime: python
api_version: 1

default_expiration: "0d"

handlers:
- url: /
  script: think/main.py
    
- url: /thought
  script: think/main.py
  
- url: /theme
  script: think/main.py

- url: /public
  script: think/main.py
  
- url: /login
  script: openidconsumer/consumer.py
  
- url: /finish
  script: openidconsumer/consumer.py
  
- url: /logout
  script: think/main.py

- url: /sessions
  script: think/session.py
  login: admin
  
- url: /stylesheets
  static_dir: static/stylesheets

- url: /images
  static_dir: static/images
  
- url: /openiduser
  static_dir: static/openiduser

- url: /js
  static_dir: static/js
  
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
    
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /sitemap.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml
  
- url: /page/.*
  script: think/main.py